// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Testingcollections.Data;

#nullable disable

namespace Testingcollections.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240309105906_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Testingcollections.Models.Advert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Adverts");
                });

            modelBuilder.Entity("Testingcollections.Models.AdvertVertical", b =>
                {
                    b.Property<int>("VerticalId")
                        .HasColumnType("int");

                    b.Property<int>("AdvertId")
                        .HasColumnType("int");

                    b.HasKey("VerticalId", "AdvertId");

                    b.HasIndex("AdvertId");

                    b.ToTable("AdvertVerticals");
                });

            modelBuilder.Entity("Testingcollections.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("Testingcollections.Models.SellerAdvert", b =>
                {
                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("AdvertId")
                        .HasColumnType("int");

                    b.HasKey("SellerId", "AdvertId");

                    b.HasIndex("AdvertId");

                    b.ToTable("SellerAdverts");
                });

            modelBuilder.Entity("Testingcollections.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("Testingcollections.Models.Vertical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Verticals");
                });

            modelBuilder.Entity("Testingcollections.Models.AdvertVertical", b =>
                {
                    b.HasOne("Testingcollections.Models.Advert", "Advert")
                        .WithMany("AdvertVerticals")
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Testingcollections.Models.Vertical", "Vertical")
                        .WithMany("AdvertVerticals")
                        .HasForeignKey("VerticalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advert");

                    b.Navigation("Vertical");
                });

            modelBuilder.Entity("Testingcollections.Models.Seller", b =>
                {
                    b.HasOne("Testingcollections.Models.State", "State")
                        .WithMany("Sellers")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("Testingcollections.Models.SellerAdvert", b =>
                {
                    b.HasOne("Testingcollections.Models.Advert", "Advert")
                        .WithMany("SellerAdverts")
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Testingcollections.Models.Seller", "Seller")
                        .WithMany("SellerAdverts")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advert");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Testingcollections.Models.Advert", b =>
                {
                    b.Navigation("AdvertVerticals");

                    b.Navigation("SellerAdverts");
                });

            modelBuilder.Entity("Testingcollections.Models.Seller", b =>
                {
                    b.Navigation("SellerAdverts");
                });

            modelBuilder.Entity("Testingcollections.Models.State", b =>
                {
                    b.Navigation("Sellers");
                });

            modelBuilder.Entity("Testingcollections.Models.Vertical", b =>
                {
                    b.Navigation("AdvertVerticals");
                });
#pragma warning restore 612, 618
        }
    }
}
